### ISSUE TITLE
When serving from webpack getting window.location is undefined

### ISSUE THREAD

**Issue by Andreew4x4** [worseisbetter/galleria#402]
I've just added Galleria to my app, and now serving from webpack dev server I'm getting:

Cannot read property 'hash' of undefined.

**Comment by it-is-just-me** [comment]
some here. I asume we're doing something wrong with webpack. But any help is appreciated

**Comment by mike-chowla** [comment]
Galleria requires access to window.location.  It took me a while to figure it out but the solution is to map `this` to `window`.

Adding the following to my webpack.config.js resolved issue:
```JavaScript
module.exports = {
    module: {
		rules: [
                        // Galleria assumes this=window
			{
				test: /galleria.*.js$/,
				loader: "imports-loader?this=>window"
			}
		]
    }
}
```

I'm using a regx since the history plugin will have issues too without it.

The next problem I had was that themes would not load correctly because they assume `Galleria` is a global.   

To fix the theme issue, I set Galleria to the window object to before loading the theme.  You need to do this from code that's part of the same webpack'ed bundle as Galleria.
```JavaScript
window.Galleria = Galleria;  // webpack
Galleria.loadTheme('../../../resources/galleria/themes/classic-1.5.7/galleria.classic.js');
```
